export const Colors = () => {
    return ([
        {
            main_color:"#e8eae8",
            secondary_color:"#646e73",
            text_color:"#2a312f",
            secondary_text_color:"#434b4e",
            button_color:"#c6cdcd"
        },
        {
            main_color:"#eee0d3",
            secondary_color:"#9a6e51",
            text_color:"#461f11",
            secondary_text_color:"#6f9ab4",
            button_color:"#e7d5bb"
        },
        {
            main_color:"#405692",
            secondary_color:"#4863ad",
            text_color:"#d9b4d7",
            secondary_text_color:"#ffffff",
            button_color:"#9192cd"
        },
        {
            main_color:"#eeeeee",
            secondary_color:"#65662f",
            text_color:"#28241b",
            secondary_text_color:"#d5d8d6",
            button_color:"#5c665f"
        },
        {
            main_color:"#d1dbed",
            secondary_color:"#ffffff",
            text_color:"#28241b",
            secondary_text_color:"#828c82",
            button_color:"#b1cdbf"
        },
        {
            main_color:"#d6dfeb",
            secondary_color:"#639ccc",
            text_color:"#194594",
            secondary_text_color:"#eeeeee",
            button_color:"#99bed9"
        },
        {
            main_color:"#fbf9f6",
            secondary_color:"#77644b",
            text_color:"#3d3925",
            secondary_text_color:"#e5cbc5",
            button_color:"#b58c85"
        },
        {
            main_color:"#333333",
            secondary_color:"#181818",
            text_color:"#f3f3f3",
            secondary_text_color:"#e5e5e5",
            button_color:"#888888"
        },
        {
            main_color:"#f3e0e7",
            secondary_color:"#e5c2ca",
            text_color:"#542b29",
            secondary_text_color:"#eeeeee",
            button_color:"#c78d96"
        },


    ]);
};